In [13]:
import os
import tweepy as tw
import pandas as pd
from IPython.display import display
import datetime


# basic settigns for tweepy
api_key = 'MslsWzWgIGUPNc2iLHM3Kbmyi'
api_secret_key = '2F91OX4ZEj8YnxjEURvaxI6ACPnjm1h0TCDreRxYkiapgTyeW3'
access_token = '1372444419073351682-Cwh5Pzh8nC8YzxHGDiOK5MAuHjByx7'
access_token_secret = '1fwg8XaNDCtTaT1yLwolRFaQzluhb6EHt7ZJGrs4AlrWN'


twitter = OAuth1Session(api_key,
                        client_secret=api_secret_key,
                        resource_owner_key=access_token,
                        resource_owner_secret=access_token_secret)

auth = tw.OAuthHandler(api_key, api_secret_key)
auth.set_access_token(access_token, access_token_secret)
api = tw.API(auth, wait_on_rate_limit=True)

# setting datetime
today = datetime.datetime.now()
today = today.replace(hour=23, minute=59, second=59, microsecond=999999) # set from the beggining of the day
time_to_the_past = 1 # 1 because we want 1 day before today
yesterday = today - datetime.timedelta(time_to_the_past) 

# Collecting tweets
count = 10 # Set the number of tweets to retrieve
next_day = yesterday + datetime.timedelta(time_to_the_past) # equivalent to today
tweets = tw.Cursor(api.search,
                   q="Biden",
                   lang="en",
                   tweet_mode='extended',
                   until = next_day.date() # format YYYY-MM-DD in datetime. Not string. Twitter only extract tweets before that date
                   ).items(count)


# Extracting desired information from each tweet
tweets_list = []

for tweet in tweets:
    # Filtering by date
    if  yesterday.date() == tweet.created_at.date(): # here we take only tweets from the same date as yesterday in format YYYY-MM-DD
        # Accessing to full_text is different between RT and normal tweet
        if 'retweeted_status' in tweet._json:  # if it is a RT take full_text
            full_text = tweet._json['retweeted_status']['full_text']
        else:  # if it is a normal tweet take the full_text
            full_text = tweet.full_text

        tweets_list.append([tweet.user.screen_name,
                             tweet.id,
                             full_text,
                             tweet.user.verified,
                             str(tweet.created_at.date()),
                             tweet.user.location,
                             tweet.user.url,
                             tweet.entities
                             ])

NameError: name 'OAuth1Session' is not defined

In [3]:
import pandas as pd
from IPython.display import display

data = pd.read_csv('labeled_data.csv')
data = data.drop(data.columns[0], axis=1)
display(data)

,count,hate_speech,offensive_language,neither,class,tweet
0,3,0,0,3,2,!!! RT @mayasolovely: As a woman you shouldn't...
1,3,0,3,0,1,!!!!! RT @mleew17: boy dats cold...tyga dwn ba...
2,3,0,3,0,1,!!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...
3,3,0,2,1,1,!!!!!!!!! RT @C_G_Anderson: @viva_based she lo...
4,6,0,6,0,1,!!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...
...,...,...,...,...,...,...
24778,3,0,2,1,1,you's a muthaf***in lie &#8220;@LifeAsKing: @2...
24779,3,0,1,2,2,"you've gone and broke the wrong heart baby, an..."
24780,3,0,3,0,1,young buck wanna eat!!.. dat nigguh like I ain...
24781,6,0,6,0,1,youu got wild bitches tellin you lies
24782,3,0,0,3,2,~~Ruffled | Ntac Eileen Dahlia - Beautiful col...

In [5]:
data['class'].value_counts()

1    19190
2     4163
0     1430
Name: class, dtype: int64

In [10]:
from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = "all"

data['tweet'][3]

'!!!!!!!!! RT @C_G_Anderson: @viva_based she look like a tranny'